jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - pwsh: |
        sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
        xcodebuild -project "./builds/macos/Soundboard.xcodeproj" -configuration Release
      displayName: Build
    - publish: '$(build.sourcesDirectory)/builds/macos/build'
      artifact: macOS
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - pwsh: |
        $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
        msbuild "./builds/win32/vs_2019/Soundboard.sln" -nologo -m -property:Configuration=Release -property:Platform="x64"
      displayName: Build
    - publish: '$(build.sourcesDirectory)/builds/win32/vs_2019/x64'
      artifact: Windows

