jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
          ./build.ps1
        pwsh: true
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
          ./build.ps1
        pwsh: true
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
          ./build.ps1 --release
        pwsh: true
    - task: CopyPublishBuildArtifacts@1
      inputs:
        CopyRoot: '$(Agent.BuildDirectory)/_build/win32/x64/Release'
        Contents: '**/*.dll'
        ArtifactName: 'Windows VST Plugin'
        ArtifactType: 'Container'