jobs:
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - pwsh: |
        sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
        ./build.ps1 --bootstrap --release
      displayName: Bootstrap
    - pwsh: |
        sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
        ./build.ps1 --configure --release
      displayName: Configure
    - pwsh: |
        sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
        ./build.ps1 --build --release
      displayName: Build
    - publish: '$(build.sourcesDirectory)/_build/macos/build/Debug'
      artifact: macOS
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - pwsh: |
        $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
        ./build.ps1 --bootstrap --release
      displayName: Bootstrap
    - pwsh: |
        $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
        ./build.ps1 --configure --release
      displayName: Configure
    - pwsh: |
        $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
        ./build.ps1 --build --release
      displayName: Build
    - publish: '$(build.sourcesDirectory)/_build/win32/x64'
      artifact: Windows

