jobs:
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - pwsh: xcodebuild
        displayName: Build
        workingDirectory: $(build.sourcesDirectory)/Builds/MacOSX
      - publish: '$(System.DefaultWorkingDirectory)/Builds/MacOSX/build/Debug'
        artifact: macOS
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - pwsh: |
        $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\;$env:PATH"
        msbuild Soundboard.sln
      displayName: Build
      workingDirectory: $(build.sourcesDirectory)/Builds/VisualStudio2019/
    - publish: '$(System.DefaultWorkingDirectory)/Builds/VisualStudio2019/x64/Debug'
      artifact: Windows
